version: '3.8'

services:

  service-produto:
    image: gustadev22/service-produto
    build:
      context: ./service-produto
      dockerfile: Dockerfile
    restart: always
    # ADICIONADO AQUI TAMBÉM SE PRECISAR DO DB LOCAL
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Aqui ele usa o nome do container do banco definido acima
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/service_produto_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USER: docker
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - 8001:8001
    networks:
      - gusta-arquitetura-network

  service-preco:
    image: gustadev22/service-preco
    build:
      context: ./service-preco
      dockerfile: Dockerfile
    restart: always
    # ISSO É O QUE VOCÊ PEDIU: Resolve o host.docker.internal dentro do container
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8002:8002
    depends_on:
      - service-imposto
    networks:
      - gusta-arquitetura-network

  service-imposto:
    image: gustadev22/service-imposto
    build:
      context: ./service-imposto
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8003:8003

    networks:
      - gusta-arquitetura-network

networks:
  gusta-arquitetura-network:
    name: gusta-arquitetura-network
    driver: bridge
