server:
  port: 8002

spring:
  application:
    name: service-preco
  management:
    tracing:
      sampling:
        probability: 1.0


resilience4j:
  retry:
    instances:
      service-preco:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  circuitbreaker:
    instances:
      service-preco:
        record-exceptions:
          - feign.FeignException

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /service-preco/v3/api-docs    # ✅ JSON aqui
  swagger-ui:
    url: /service-preco/v3/api-docs