name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches: 
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'


# Build - Temos dois processos de build. O primeiro,
# com o run mvn spring-boot:build-image para aqules cujo configuracao
# esta no pom.xml. ja a outra é com run clean package cujo utiliza
# dockerfile.

    - name: Build Eureka Naming Server Docker Image
      working-directory: ./naming-server
      run: mvn spring-boot:build-image

    - name: Build Api Gateway Docker Image
      working-directory: ./api-gateway
      run: mvn spring-boot:build-image

    - name: Build Service Imposto Docker Image
      working-directory: ./service-imposto
      run: mvn clean package
    
    - name: Build Service Preco Docker Image
      working-directory: ./service-preco
      run: mvn clean package
    
    - name: Build Service Produto
      working-directory: ./service-produto
      run: mvn clean package

    - name: Tag Docker images
      run: |
        docker tag ${{secrets.DOCKER_USERNAME}}/naming-server-arquitetura:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/naming-server-arquitetura:latest
        docker tag ${{secrets.DOCKER_USERNAME}}/naming-server-arquitetura:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/naming-server-arquitetura:${{github.RUN_ID}}
        
        docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway-arquitetura:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/api-gateway-arquitetura:latest
        docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway-arquitetura:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/api-gateway-arquitetura:${{github.RUN_ID}}
        
#        docker tag ${{secrets.DOCKER_USERNAME}}/service-imposto:latest ${{secrets.DOCKER_USERNAME}}/service-imposto:latest
#        docker tag ${{secrets.DOCKER_USERNAME}}/service-imposto:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/service-imposto:${{github.RUN_ID}}
        docker tag ${{secrets.DOCKER_USERNAME}}/service-preco:latest ${{secrets.DOCKER_USERNAME}}/service-preco:${{github.RUN_ID}}
        docker tag ${{secrets.DOCKER_USERNAME}}/service-produto:latest ${{secrets.DOCKER_USERNAME}}/service-produto:${{github.RUN_ID}}
        
    - name: Push Docker Images to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/naming-server-arquitetura:latest
        docker push ${{secrets.DOCKER_USERNAME}}/naming-server-arquitetura:${{github.RUN_ID}}
        
        docker push ${{secrets.DOCKER_USERNAME}}/api-gateway-arquitetura:latest
        docker push ${{secrets.DOCKER_USERNAME}}/api-gateway-arquitetura:${{github.RUN_ID}} 
#        
#        docker push ${{secrets.DOCKER_USERNAME}}/service-imposto:latest
#        docker push ${{secrets.DOCKER_USERNAME}}/service-imposto:${{github.RUN_ID}}
##
        docker push ${{secrets.DOCKER_USERNAME}}/service-preco:latest
        docker push ${{secrets.DOCKER_USERNAME}}/service-preco:${{github.RUN_ID}}

        docker push ${{secrets.DOCKER_USERNAME}}/service-produto:latest
        docker push ${{secrets.DOCKER_USERNAME}}/service-produto:${{github.RUN_ID}}
#        
#        

